# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: keda-aks-pool

jobs:
- job: Job_One
  displayName: 'Job One - Single Line Script'
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
 
- job: Job_Two
  displayName: 'Job Two - Multi Line Script'
  dependsOn: Job_One
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
    
- job: Job_Three
  displayName: 'Job Three - Verify Git LFS'
  dependsOn: Job_Two
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      echo "Checking Git LFS version..."
      git lfs version
    displayName: 'Verify Git LFS is Installed'   